### ISSUE TITLE
Find a BDD framework

### ISSUE THREAD

**Issue by jpigree** [crucibuild/sdk-agent-go#11]
### Task:

Find a suitable BDD framework and translate existing unit tests.

**Comment by jpigree** [comment]
As pointed out by @ccamel, in order to have even better unittests, we will need a BDD framework.
We already found those:
- https://onsi.github.io/ginkgo/
- https://github.com/franela/goblin
Or even more extreme (write tests in cucumber):
- https://github.com/DATA-DOG/godog

**Comment by jpigree** [comment]
Okay. After a few research, Go Convey seems to be the most suited for us (https://github.com/smartystreets/goconvey). 

Mainly for those reasons:
- natively useable with "go test"
- Simple DSL
- Popular on Github (>2900 stars)
- Sweet web GUI for displaying results
- wrote in Go

**Comment by jpigree** [comment]
We now need to transcribe our current tests into Go Convey DSL before closing this issue.

**Comment by ccamel** [comment]
Great. It sounds really good to me. The _DSL_ of [Go Convey](https://github.com/smartystreets/goconvey) is really nice in terms of expressivity and potentiality.

So we can go with it. :+1:
