### ISSUE TITLE
Prevent Go projects builds to be broken by dependencies breaking changes

### ISSUE THREAD

**Issue by jpigree** [crucibuild/sdk-agent-go#21]
### Task

Since the paradigm in Go is to always use the latest version of the projects, it also means than a upstream breaking change can impact our projects without a commit yet all our builds are triggered by push only.

In order to adress this issue, I propose to setup a daily cron build on all our projects. This will enable us to track breakage and fix them on a daily basis.

**Comment by jpigree** [comment]
@ccamel I just setup this in travis. Each day, sdk-agent-go and agent-go-examples will be built from scratch. Trigger a build from agent-go-example when sdk-agent-go master's is updated, would not have been a complete solution to the problem of dependencies (mainly because sdk-agent-go isn't the only dependency of the project).

I think we should setup this on each of our Go projects from now on.

**Comment by ccamel** [comment]
As far as I understand, you propose also to build the sdk every day ? Do you fear that a lib that we depends on breaks our build?

**Comment by jpigree** [comment]
Yes. This was my point. We will be okay now because we are frequently modifying it but when it will be stabilized we should have a way to continuously test if it is okay.
