### ISSUE TITLE
Improve build process (Makefile)

### ISSUE THREAD

**Issue by ccamel** [crucibuild/sdk-agent-go#3]

**Comment by jpigree** [comment]
I don't understand. The examples are built by the Makefile.

**Comment by ccamel** [comment]
That's really strange. It doesn't work on my configuration.

**Comment by ccamel** [comment]
It seems that 'go build -v ./...' build and _install_ the examples. They are not available localy (at the root of the project) but installed in the go environment.

**Comment by jpigree** [comment]
Okay. Yes. It does not put the binaries on your root. But to me, this is a wanted behaviour. I prefer having the executables installed cleanly than put directly on my root directory with all my source code.

**Comment by jpigree** [comment]
What is the use case that makes the installed executables lesser handy than the generated on root dir binaries?

**Comment by ccamel** [comment]
I believe there is a side effect here which bypasses the canonical behaviour of go.

If I look to a command line tool written in go:

- when I invoke:
```
go get ./...
```
no build is performed, but only the dependencies are retrieved, build and installed.

- when I invoke:
```
go build .
```
the build is performed, and the executable is available localy in the root of the project.

- when I invoke:
```
go install .
```
the build is performed (if needed), and the executable is available in the system.

So, as far as I understand, the installation issue is due to that specific go invokation:
```
go get ./...
```
which download the example agents _as dependencies_, with build and installation stages. And unfortunately, as we don't have any go code at the project root, we can't use the following command line: "go get ."

**Comment by ccamel** [comment]
Another problem arises with the generation of code needed to build the examples. You can't simply type this to get the binaries (as it should be):
```
go get github.com/crucibuild/sdk-agent-go/example/agent-ping  
```

You get a "panic: runtime error" as you mentioned already.

**Comment by jpigree** [comment]
Yes. I think, we need to include the generation of the code in the go build step. However, I don't get it. examples aren't a dependency of anyone.How could they be installed when doing "go get"?

**Comment by ccamel** [comment]
The code generation can be included in the go build step by using the _go generate_ tool (see https://blog.golang.org/generate).

I started using it with genny (ee86644). To have _go generate_ drive the process, you just need to add a special comment in one of the go giles. In our case it may be in the file declaring the main package.

**Comment by jpigree** [comment]
The guy of go-resources warned about not including the generation of resources in go-generate.
=> https://github.com/omeid/go-resources#go-generate

**Comment by ccamel** [comment]
I don't completely subscribe to the point of view, but I may be wrong. I would rather advocate to follow the way of inclusion of external resources by the adapted go tool, i.e. _go generate_ available as of go 1.4, as discussed here: https://stackoverflow.com/questions/17796043/embedding-text-file-into-compiled-executable

**Comment by ccamel** [comment]
May I edit/rename this issue to something more in connection with what is being discussed here ?

**Comment by jpigree** [comment]
Yep Do it. :)

**Comment by jpigree** [comment]
The solution adopted is finally to move the examples into another repository (github.com/crucibuild/agent-go-examples).
